### PR TITLE
Voltaire upgrade

### PR DESCRIPTION
**Pull request by emmamarichal**
Hello @EbenSorkin!

Here you can find the modifications for the Voltaire upgrade.
No big changes, the font works great, bravo and thanks! 

Cheers!

### CODE REVIEW

**Comment by emmamarichal** [comment]
@EbenSorkin I updated Authors and contributors that were empty. 
However, I don't have the email Yvonne Schüttler (in authors), so feel free to complete it once you merge this PR.

Thanks :)

**Comment by EbenSorkin** [comment]
I have a historical email which would fill the gap technically but it
doesn't seem to be valid anymore so maybe it's better that be blank than
false.

I have looked for a new email but I have not been able to find one.

IDK if this is because Yvonne has become an internet hermit or changed her
name or what.

Maybe skip tracing or a social means will find her.

I'll ask a mutual teacher and ex-classmates and see if anyone knows and get
back to you.

-e.

**Comment by emmamarichal** [comment]
Super, thank you! Maybe we can still onboard the font now, and you can add the email later in the repo (in Authors and in the readme).

**Comment by emmamarichal** [comment]
Hi @EbenSorkin, could you merge this PR please? Thanks! 😊

**Comment by EbenSorkin** [comment]
I have merged the PR and made some improvements ( more language support ) and fixed bugs arising from migrating to Glyphs 3 source from Glyphs 2 source. Kerning is also redone. I think this is ready for your review and maybe for publishing.

**Pull request merged**
