### PR TITLE
Accents updated

### PR DESCRIPTION
**Pull request by emmamarichal**
Hello @EbenSorkin,

Sorry for this new PR, but some anchor bugs were noticed right before the font onboarding.
200833279-803e70c1-56a3-4061-a49a-2e85657a9014

So I reviewed a bit all the accents, I used the automatic alignment, replaced legacy accents by comb accents etc. 
In the source, you will find the previous version in the background if you want to take a look. 

Thank you, 
Cheers!

### CODE REVIEW

**Comment by EbenSorkin** [comment]
There seem to be a couple of surprises in this file that would need to be
fixed maybe -

• It looks like the source was migrated from Glyphs 2 to 3. I recall
reading that Glypsh to was still preferable in the GF workflow. Has this
changed?
• Z had an anchor position that was unexpected/wrong
• Glyphs that should be using auto alignment and position etc were not.
This might be a result of an unsuccessful transition from Glyphs 2 to 3 or
may just be an error on my part. I noticed this while fixing a problem
with  Z and comparing it to the Ohorntilde which I also noticed an issue
with.

I suggest that we go back to a Glyphs 2 source (unless that's no longer
ideal) and that we ( I?) make sure the glyphs that should be composed from
components are composed correctly.

-e.

**Comment by emmamarichal** [comment]
Hi @EbenSorkin,

For the 'Z', in deed I forgot to correct this anchor.
What is the issue you saw with Ohorntilde? I don't see it

And yes, as I said in the chat, I didn't use automatic alignment everywhere, because it strongly modified the spacing.
So either you do it to have better control over it, or I'll take care of it and let you validate it afterwards.

I'm not sure if it's a Glyphs version problem, did you on your side have these anchor position problems with Glyphs 2?

**Comment by emmamarichal** [comment]
@EbenSorkin, I'm reviewing the last version you made, with the automatic alignment.
There were still few bad positions of anchors, but easy to correct. 

I have a question concerning the glyph Eng:
Capture d’écran 2022-11-11 à 17 37 05

Is it normal that the top left isn't the same? Tell me what do you think and I'll correct that or not :)

Thanks!
Emma

**Comment by EbenSorkin** [comment]
Good point! I agree - they should match. Thanks for finding the anchor
issues!

**Pull request merged**
